version: "3.9"
services:
    cwcmtest:
        image: php:8-fpm-alpine
        restart: unless-stopped
        volumes:
            - /home/vsavakhande/Projects/php8cwcm/src/www:/var/www/html/cwcmtest
            - ./logs:/var/log
        networks:
            - cex
networks:
    cex:
        driver: bridge
        name: cex